language: python
dist: xenial
python: 3.7
install:
  - pip install pipenv
  - pipenv install
env: # Add builds here
  # Run pytest and generate coverage report
  - CMD="pipenv run pytest --cov=effloresce"
  # Run black and report
  - CMD="black --check --verbose ."
script:
  - $CMD
after_success:
  - coveralls
