language: python
dist: xenial
python: 3.7
install:
  - pip install pipenv
  - pipenv install
script:
  - $CMD
env: # Add builds here
  - CMD="pipenv run pytest --cov=effloresce"
after_success:
  - coveralls
